### ISSUE TITLE
cant start

### ISSUE THREAD

**Issue by knottty** [matthewmiglio/py-clash-bot#33]
C:\Users\Tim\Desktop\bot>pyclashbot
Traceback (most recent call last):
  File "c:\users\tim\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\tim\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tim\AppData\Local\Programs\Python\Python38\Scripts\pyclashbot.exe\__main__.py", line 4, in <module>
  File "c:\users\tim\appdata\local\programs\python\python38\lib\site-packages\pyclashbot\__main__.py", line 9, in <module>
    from pyclashbot.battlepass import check_if_can_collect_bp, collect_bp
  File "c:\users\tim\appdata\local\programs\python\python38\lib\site-packages\pyclashbot\battlepass.py", line 4, in <module>
    from pyclashbot.client import check_quit_key_press, click, screenshot, scroll_down, scroll_down_fast, scroll_up_fast
  File "c:\users\tim\appdata\local\programs\python\python38\lib\site-packages\pyclashbot\client.py", line 9, in <module>
    from pyclashbot.image_rec import check_for_location, find_references, get_first_location
  File "c:\users\tim\appdata\local\programs\python\python38\lib\site-packages\pyclashbot\image_rec.py", line 12, in <module>
    def get_first_location(locations: list[Union[list[int], None]], flip=False):
TypeError: 'type' object is not subscriptable

**Comment by marmig0404** [comment]
This error is caused by Python 3.8 not supporting the typing syntax in this module, try upgrading to 3.10.
